version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/ebedke

    steps:
      - checkout
      - run:
          name: Install
          command: |
            poetry install
      - run:
          name: Setup config
          command: |
            cp ~/ebedke/ebedke/config.py.example ~/ebedke/ebedke/config.py
      - run:
          name: Test
          command: |
            poetry run pytest
